### ISSUE TITLE
Crash on Android 4: java.lang.NoSuchMethodError: no method with name='setNestedScrollingEnabled'

### ISSUE THREAD

**Issue by felixkrautschuk** [triniwiz/nativescript-pager#162]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

On our Android 4 device, the app crashes when navigating to a page that contains the pager:

> System.err: An uncaught Exception occurred on "main" thread.
> System.err: Calling js method onCreateView failed
> System.err: Error: java.lang.NoSuchMethodError: no method with name='setNestedScrollingEnabled' signature='(Z)V' in class Landroid/view/View;
> System.err: StackTrace:
> System.err: push.../node_modules/nativescript-pager/pager.js.Pager.createNativeView(file:///node_modules/nativescript-pager/pager.js:115:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase._setupUI(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:497:0)
> System.err:     at (file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:539:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView(file:///node_modules/@nativescript/core/ui/layouts/layout-base-common.js:125:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view-common.js.ViewCommon.eachChild(file:///node_modules/@nativescript/core/ui/core/view/view-common.js:915:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase._setupUI(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:538:0)
> System.err:     at (file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:539:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/content-view/content-view.js.ContentView.eachChildView(file:///node_modules/@nativescript/core/ui/content-view/content-view.js:70:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/page/page-common.js.PageBase.eachChildView(file:///node_modules/@nativescript/core/ui/page/page-common.js:126:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view-common.js.ViewCommon.eachChild(file:///node_modules/@nativescript/core/ui/core/view/view-common.js:915:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase._setupUI(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:538:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase._addViewCore(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:437:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase._addView(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:426:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/frame/frame.js.FragmentCallbacksImplementation.onCreateView(file:///node_modules/@nativescript/core/ui/frame/frame.js:700:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/frame/fragment.js.FragmentClass.onCreateView(file:///node_modules/@nativescript/core/ui/frame/fragment.js:29:0)
> System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
> System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
> System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
> System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1160)
> System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1138)
> System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1134)
> System.err:     at com.tns.FragmentClass.onCreateView(FragmentClass.java:53)
> System.err:     at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
> System.err:     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
> System.err:     at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
> System.err:     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
> System.err:     at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
> System.err:     at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
> System.err:     at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
> System.err:     at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
> System.err:     at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
> System.err:     at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
> System.err:     at android.os.Handler.handleCallback(Handler.java:733)
> System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
> System.err:     at android.os.Looper.loop(Looper.java:146)
> System.err:     at android.app.ActivityThread.main(ActivityThread.java:5593)
> System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
> System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
> System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
> System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
> System.err:     at dalvik.system.NativeStart.main(Native Method)
> System.err: Caused by: java.lang.NoSuchMethodError: no method with name='setNestedScrollingEnabled' signature='(Z)V' in class Landroid/view/View;
> System.err:     ... 26 more
> ActivityManager: Process org.nativescript.NSPagerIssueIOS (pid 24762) (adj 0) has died.

### Which platform(s) does your issue occur on?
- Android
- 4.2, 4.4
- tested on Emulator and Samsung Galaxy S4 mini

The crash does not occur on Android >= 5

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it) 6.4.1
- Cross-platform modules: 6.4.1
- Runtime(s): tns-android 6.4.1
- Plugin(s): nativescript-pager 12.0.0-alpha.3

### Please, tell us how to recreate the issue in as much detail as possible. 
Just open the app and tap the button to navigate to the page that contains the pager component.

### Is there any code involved? 
[NSPagerIssueAndroid_4.zip](https://github.com/triniwiz/nativescript-pager/files/4250298/NSPagerIssueAndroid_4.zip)

**Comment by felixkrautschuk** [comment]
@triniwiz unfortunately, the issue still occurs on Android 4 using 12.0.0-alpha.4

**Comment by felixkrautschuk** [comment]
I believe this issue is caused by this line:
https://github.com/triniwiz/nativescript-pager/blob/master/src/pager.android.ts#L125

```
if (sdkVersion => 21) {        //  "=>" should be ">="
    this._pager.setNestedScrollingEnabled(true);
}
```
