### ISSUE TITLE
This plugin doesn't seems to be working with NS Module Loader (option lazy)

### ISSUE THREAD

**Issue by mpochron** [triniwiz/nativescript-pager#37]
I don't need to describe more here. Just as title.

app-routing.ts:
``` 
   {
        path: "home",
        loadChildren: "./views/dummy/dummy.module#DummyModule"
    },        
```

dummy.module.ts:
```
import { NgModule, NO_ERRORS_SCHEMA } from "@angular/core";
import { NativeScriptCommonModule } from "nativescript-angular/common";

import { DummyRoutingModule } from "./dummy-routing.modules";
import { DummyComponent } from "./dummy.component";
import { ReactiveFormsModule } from "@angular/forms";

@NgModule({
    imports: [
        NativeScriptCommonModule,
        ReactiveFormsModule,
        // SharedModule,
        DummyRoutingModule,
    ],
    declarations: [
        DummyComponent,
    ],
    schemas: [
        NO_ERRORS_SCHEMA,
    ],
})
export class DummyModule {}

```

test.component.html
```
<ActionBar title="My NG Demo" class="action-bar">
</ActionBar>
<GridLayout rows="*, auto" columns="*" class="page">
    <Pager [items]="items | async" #pager [selectedIndex]="currentPagerIndex" (selectedIndexChange)="onIndexChanged($event)" class="pager">
        <ng-template pagerItemTemplate let-i="index" let-item="item">
            <GridLayout class="pager-item" rows="auto, *" columns="*" backgroundColor="red">
                <Label [text]="item.title"></Label>
                <Image stretch="fill" row="1" [src]="item.image"></Image>
            </GridLayout>
        </ng-template>
    </Pager>

    <DockLayout row="1" orientation="horizontal" stretchLastChild="true" class="bg-primary">
        <Button dock="left" text="Prev" (tap)="prevPage()" class="btn btn-primary"></Button>
        <Button dock="right" text="Next" (tap)="nextPage()" class="btn btn-primary"></Button>
        <Button text="nav" [nsRouterLink]="['/dummy']" class="btn btn-primary"></Button>
    </DockLayout>
</GridLayout>
```

Error

```
ystem.err: com.tns.NativeScriptException:
System.err: Calling js method instantiateItem failed
System.err: TypeError: Cannot read property 'nativeView' of null
System.err: File: "file:///data/data/org.nativescript.demong/files/app/tns_modules/nativescript-pager/src/android/pager.js, line: 242, column: 31
System.err: StackTrace:
System.err:     Frame: function:'PagerAdapter.instantiateItem', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/nativescript-pager/src/android/pager.js', line: 242, column: 32
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
```

**Comment by sean-perkins** [comment]
What does your `items` collection look like? How is that observable collection populated?

We use this plugin in a lazy-loaded module without those listed problems (iOS and Android).

**Comment by mpochron** [comment]
with attribute async: 
```
export class DummyComponent {
items: any;

    constructor() {
        this.items = new BehaviorSubject([
            {
                title: "Slide 1",
                image: "~/images/Hulk_(comics_character).png"
            },
            {
                title: "Slide 2",
                image: "https://s-media-cache-ak0.pinimg.com/originals/4c/92/cc/4c92cc1dfbde6a6a40fe799f56fa9294.jpg"
            }])
   }

}

```
or without attribute `async` maybe items with `items:any = [{id:0}, {id: 1}];`


fine works without loadChildren inside routing, i dont know how to implement this component in mode lazy

**Comment by sean-perkins** [comment]
Perhaps try moving the items instantiation to an `ngOnInit` life-cycle hook. 

Our implementation is like:
```
 <Pager [items]="banners$ | async" (selectedIndexChange)="onIndexChanged($event)" #bannerEl>
        <ng-template pagerItemTemplate let-banner="item" let-i="index">
            <GridLayout paddingLeft="10" paddingRight="10">
                <loop-banner [banner]="banner" [expanded]="bannerExpanded"></loop-banner>
            </GridLayout>
        </ng-template>
    </Pager>
```

where `banners$` is an observable subscription to ngrx state:

```
this.banners$ = this.store$.select(getBanners);
```

This lives in our DashboardComponent, which is part of a lazy-loaded module:

```
 {
                path: 'dashboard',
                children: [
                    { path: '', pathMatch: 'full', redirectTo: 'user' },
                    {
                        path: 'user',
                        loadChildren:
                            './+dashboard-user/dashboard-user.module#DashboardUserModule'
                    }
                ]
            },
```

**Comment by mpochron** [comment]
Sorry, it doesn't solve my problem.

**Comment by triniwiz** [comment]
@mpochron still receiving the same error after upgrading to the latest ?

**Comment by mpochron** [comment]
After upgrading to the latest works! thanks :D

**Comment by mpochron** [comment]
@triniwiz 

![image](https://user-images.githubusercontent.com/7736131/35337770-538e09fe-011c-11e8-9fe9-eeb7f02700dd.png)

```
import { NgModule } from "@angular/core";
import { NativeScriptRouterModule } from "nativescript-angular/router";
import { Routes } from "@angular/router";

import { TestComponent } from "./test/test.component";
import { TestMultiComponent } from './test-multi/test-multi.component';
import { DummyComponent } from "./dummy.component";

const routes: Routes = [
  { path: '', redirectTo: '/test', pathMatch: 'full' },
  { path: 'test', component: TestComponent },
  { path: 'multi', component: TestMultiComponent },
  { 
    path: 'dummy', 
    loadChildren: "./dummy/dummy.modules#DummyModule",
  }
];

@NgModule({
    imports: [NativeScriptRouterModule.forRoot(routes)],
    exports: [NativeScriptRouterModule]
})
export class AppRoutingModule { }
```

After using loadChildren still keeps to show `[object Object]`. Please ASAP fix it.

**Comment by triniwiz** [comment]
A work around you can try is getting the pager instance then call `pagerInstance.reload(true)`

**Comment by EddyVerbruggen** [comment]
@triniwiz I wouldn't fix anything for anyone shouting "ASAP" at me.

**Comment by mpochron** [comment]
Oh found bug. 

```
            <Pager [items]="contacts | async" #pager class="pager" showNativePageIndicator="true">
                <ng-template pagerItemTemplate let-i="index" let-item="item">
         <StackLayout>

                        <Label *ngFor="let contact of item" [text]="contact.firstName"></Label>

                    </StackLayout>
                </ng-template>
            </Pager>
```

From the beginning method ngFor was the reason. Without ngFor well works. Any idea how to fix and use ngFor in that situation?

**Comment by triniwiz** [comment]
You can try upgrading

**Comment by mpochron** [comment]
But thanks, i found other answer thanks to creating custom component where can have ngFor.
